### ISSUE TITLE
Separate clibdpa core and its extensions

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/clibdpa#12]
- is it good idea? benefits?
- do we leave transactions in the core of the library?

**Comment by fmikulu** [comment]
- clibdpa core shall contain all generic handling, it means transactions as well - files DpaTask and DpaTransactionTask
- extensions shall contain all Prf or their equivalents

extension is gonna be growing, but clibdpa shall be rather stable compact and tested appropriately. From this POV it makes sense to split the libs

**Comment by spinarr** [comment]
1+
Lets move DpaTask.cpp and DpaTransactionTask.cpp files into Dpa folder.

**Comment by spinarr** [comment]
Done in review-insteps.
