### ISSUE TITLE
Is there better way to deal with timing of discovery?

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/clibdpa#22]
It is now possible to define timeout:0, meaning waiting infinite until response comes.

This can lead and indeed led to blocking of iqrf interface when there is no response
(e.g. node is off and someone defines timeout:0 by mistake)

Any ideas?

**Comment by spinarr** [comment]
Timeout 0 has been primarily defined for discovery command where we do not know how long it will run.

We could potentially run discovery and then checking IChannel till it gets ready. During discovery
SPI is stoped by the coordinator.

So timeout 0 would mean to wait till the IChannel is ready.

**Comment by fmikulu** [comment]
The *discovery* command will be checked just before DpaTransaction execution as PCMD = 0x07 value. This will be considered as the only one situation with timeout = 0 => infinite waiting. In other situations if an explicit passed timeout is < 200 ms it is silently replaced by minimum 200 ms (with WARNING trace)

There is a possibility to utilize SPI ready check "in case" but it seems superfluous now.

**Comment by spinarr** [comment]
ok, we leave out spi check
