### ISSUE TITLE
Next steps in clibdpa maintenance

### ISSUE THREAD

**Issue by fmikulu** [iqrfsdk/clibdpa#27]
As we introduced clibdpa2 redesign, there is a question how to continue with clibdpa maintenance I can see these possibilities:
1. Keep clibdpa as it is and introduce a new repo clibdpa2 (ore better name)
2. Leave clibdpa as it is and move clibdpa2 as a part of IqrfDpa component in iqrf-daemon V2. It means discontinue clibdpa2 as independent library. **It is my preference**
3. Make clibdpa release v1.0.0 with existing implementation and continue in master with V2 and provide v2.0.0 after testing

@spinarr @michal-konopa and others -Opinion?

**Comment by fmikulu** [comment]
Explanation of my preference 2nd - all these features are more flexible in component system:
- clibdpa2 requires an interface to IQRF coordinator
- clbdpa2  provides an interface to upper layers
- usage of Trace system
- possible usage of other features  - configuration, statistic, heart beet, etc.

But it can be solved in case of independent clibdpa with some additional wrappers in component indeed.

**Comment by spinarr** [comment]
I would leave master clibdpa for iqrfd1 and develop clibdpa for iqrfd2.
Once ready develop will be moved to master.

**Comment by fmikulu** [comment]
That's existing situation, so no change for now?

**Comment by fmikulu** [comment]
@spinarr are we ready to maintain old version in v1.0.0 branch and continue with clibdpa2 in master?

**Comment by spinarr** [comment]
Yes. 

v1.1.0
https://github.com/iqrfsdk/clibdpa/tree/release/v1.1.0

v2.0.0
https://github.com/iqrfsdk/clibdpa/tree/master

**Comment by spinarr** [comment]
https://github.com/iqrfsdk/clibdpa/tree/master/Dpa

- are there classes that are not needed anymore wrt to handler2?
- can handler2 broken into more files/per class?

**Comment by fmikulu** [comment]
We can split indeed. Lets do it after freezing of v1.1.0 and continuation with v2 only in master branch
