### ISSUE TITLE
Include Tracer component for tests and debug

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/clibdpa#9]
- Add Tracer to the library to test the timing and processing
- Where to initialize Tracer to be used across the library?

**Comment by fmikulu** [comment]
It's not a big deal. It's already there in some files, but I added include path to Dpa target: 75f23a32ca6107a9db90200856efa1e9c9fbc6cf

There has to be one TRC_INIT in compilation unit (exe or shared lib). If everything build statically it has to be somewhere, e.g. close to main(). As a part of existing apps (daemon, example, etc.) it is already there. So just use TRC_ macros or other tracing functions.

**Comment by spinarr** [comment]
Done in basic example in review-insteps.
